apiVersion: v1
kind: Service
metadata:
  name: crawler-service
spec:
  selector:
    app: synergychat-crawler
  ports:
    - protocol: TCP
      port: 80 # port that the server will listen on
      targetPort: 8080 # port that the pods are listening on

